DROP TABLE IF EXISTS ticket CASCADE;
DROP TABLE IF EXISTS seat CASCADE;
DROP TABLE IF EXISTS ticket_user CASCADE;

CREATE TABLE ticket_user (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    created_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone_number VARCHAR(20),
    address VARCHAR(255)
);

CREATE TABLE seat (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    created_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    section VARCHAR(255) NOT NULL,
    seat_number VARCHAR(255) NOT NULL,
    is_booked BOOLEAN,
    ticket_id BIGINT,
    FOREIGN KEY (ticket_id) REFERENCES ticket(id)
);

CREATE TABLE ticket (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    created_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    user_id BIGINT NOT NULL,
    boarding_station VARCHAR(255) NOT NULL,
    destination_station VARCHAR(255) NOT NULL,
    ticket_price INT NOT NULL DEFAULT 5,
    travel_date DATE NOT NULL,
    booking_date DATE NOT NULL,
    FOREIGN KEY (user_id) REFERENCES ticket_user(id)
);

ALTER TABLE seat ADD CONSTRAINT FK_ticket FOREIGN KEY (ticket_id) REFERENCES ticket(id);